# Plan9
SYSCFLAGS = -D_SUSV2_SOURCE

# NetBSD
CC1_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE
CC2_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE
AS_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE

# OpenBSD
CC1_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE
CC2_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE
AS_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE

# FreeBSD
CC1_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE
CC2_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE
AS_CFLAGS = -D_ISOC99_SOURCE -D_ANSI_SOURCE

